# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_c_comand')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_c_comand')
    _c_comand = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_c_comand', [dirname(__file__)])
        except ImportError:
            import _c_comand
            return _c_comand
        try:
            _mod = imp.load_module('_c_comand', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _c_comand = swig_import_helper()
    del swig_import_helper
else:
    import _c_comand
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

try:
    import weakref
    weakref_proxy = weakref.proxy
except __builtin__.Exception:
    weakref_proxy = lambda x: x


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _c_comand.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _c_comand.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _c_comand.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _c_comand.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _c_comand.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _c_comand.SwigPyIterator_equal(self, x)

    def copy(self):
        return _c_comand.SwigPyIterator_copy(self)

    def next(self):
        return _c_comand.SwigPyIterator_next(self)

    def __next__(self):
        return _c_comand.SwigPyIterator___next__(self)

    def previous(self):
        return _c_comand.SwigPyIterator_previous(self)

    def advance(self, n):
        return _c_comand.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _c_comand.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _c_comand.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _c_comand.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _c_comand.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _c_comand.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _c_comand.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _c_comand.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class PairDeque(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PairDeque, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PairDeque, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _c_comand.PairDeque_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _c_comand.PairDeque___nonzero__(self)

    def __bool__(self):
        return _c_comand.PairDeque___bool__(self)

    def __len__(self):
        return _c_comand.PairDeque___len__(self)

    def __getslice__(self, i, j):
        return _c_comand.PairDeque___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _c_comand.PairDeque___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _c_comand.PairDeque___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _c_comand.PairDeque___delitem__(self, *args)

    def __getitem__(self, *args):
        return _c_comand.PairDeque___getitem__(self, *args)

    def __setitem__(self, *args):
        return _c_comand.PairDeque___setitem__(self, *args)

    def pop(self):
        return _c_comand.PairDeque_pop(self)

    def append(self, x):
        return _c_comand.PairDeque_append(self, x)

    def empty(self):
        return _c_comand.PairDeque_empty(self)

    def size(self):
        return _c_comand.PairDeque_size(self)

    def swap(self, v):
        return _c_comand.PairDeque_swap(self, v)

    def begin(self):
        return _c_comand.PairDeque_begin(self)

    def end(self):
        return _c_comand.PairDeque_end(self)

    def rbegin(self):
        return _c_comand.PairDeque_rbegin(self)

    def rend(self):
        return _c_comand.PairDeque_rend(self)

    def clear(self):
        return _c_comand.PairDeque_clear(self)

    def get_allocator(self):
        return _c_comand.PairDeque_get_allocator(self)

    def pop_back(self):
        return _c_comand.PairDeque_pop_back(self)

    def erase(self, *args):
        return _c_comand.PairDeque_erase(self, *args)

    def __init__(self, *args):
        this = _c_comand.new_PairDeque(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _c_comand.PairDeque_push_back(self, x)

    def front(self):
        return _c_comand.PairDeque_front(self)

    def back(self):
        return _c_comand.PairDeque_back(self)

    def assign(self, n, x):
        return _c_comand.PairDeque_assign(self, n, x)

    def resize(self, *args):
        return _c_comand.PairDeque_resize(self, *args)

    def insert(self, *args):
        return _c_comand.PairDeque_insert(self, *args)

    def pop_front(self):
        return _c_comand.PairDeque_pop_front(self)

    def push_front(self, x):
        return _c_comand.PairDeque_push_front(self, x)
    __swig_destroy__ = _c_comand.delete_PairDeque
    __del__ = lambda self: None
PairDeque_swigregister = _c_comand.PairDeque_swigregister
PairDeque_swigregister(PairDeque)

class StopIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StopIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StopIterator, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _c_comand.new_StopIterator()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _c_comand.delete_StopIterator
    __del__ = lambda self: None
StopIterator_swigregister = _c_comand.StopIterator_swigregister
StopIterator_swigregister(StopIterator)

class WaveIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, WaveIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, WaveIterator, name)
    __repr__ = _swig_repr

    def __init__(self, _cur, _end):
        this = _c_comand.new_WaveIterator(_cur, _end)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def __iter__(self):
        return _c_comand.WaveIterator___iter__(self)
    __swig_setmethods__["cur"] = _c_comand.WaveIterator_cur_set
    __swig_getmethods__["cur"] = _c_comand.WaveIterator_cur_get
    if _newclass:
        cur = _swig_property(_c_comand.WaveIterator_cur_get, _c_comand.WaveIterator_cur_set)
    __swig_setmethods__["end"] = _c_comand.WaveIterator_end_set
    __swig_getmethods__["end"] = _c_comand.WaveIterator_end_get
    if _newclass:
        end = _swig_property(_c_comand.WaveIterator_end_get, _c_comand.WaveIterator_end_set)

    def __next__(self):
        return _c_comand.WaveIterator___next__(self)

    def next(self):
        return _c_comand.WaveIterator_next(self)
    __swig_destroy__ = _c_comand.delete_WaveIterator
    __del__ = lambda self: None
WaveIterator_swigregister = _c_comand.WaveIterator_swigregister
WaveIterator_swigregister(WaveIterator)

class WAVE(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, WAVE, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, WAVE, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _c_comand.new_WAVE(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _c_comand.delete_WAVE
    __del__ = lambda self: None

    def set_delay(self, d):
        return _c_comand.WAVE_set_delay(self, d)

    def initialize(self):
        return _c_comand.WAVE_initialize(self)

    def push(self, t, v):
        return _c_comand.WAVE_push(self, t, v)

    def v_out(self, t):
        return _c_comand.WAVE_v_out(self, t)

    def v_reflect(self, t, v_total):
        return _c_comand.WAVE_v_reflect(self, t, v_total)

    def __iadd__(self, *args):
        return _c_comand.WAVE___iadd__(self, *args)

    def __imul__(self, *args):
        return _c_comand.WAVE___imul__(self, *args)

    def begin(self):
        return _c_comand.WAVE_begin(self)

    def end(self):
        return _c_comand.WAVE_end(self)

    def __iter__(self):
        return _c_comand.WAVE___iter__(self)
WAVE_swigregister = _c_comand.WAVE_swigregister
WAVE_swigregister(WAVE)

class CKT_BASE(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CKT_BASE, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CKT_BASE, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    if _newclass:
        find_wave = staticmethod(_c_comand.CKT_BASE_find_wave)
    else:
        find_wave = _c_comand.CKT_BASE_find_wave
CKT_BASE_swigregister = _c_comand.CKT_BASE_swigregister
CKT_BASE_swigregister(CKT_BASE)

def CKT_BASE_find_wave(arg2):
    return _c_comand.CKT_BASE_find_wave(arg2)
CKT_BASE_find_wave = _c_comand.CKT_BASE_find_wave

class CMD(CKT_BASE):
    __swig_setmethods__ = {}
    for _s in [CKT_BASE]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, CMD, name, value)
    __swig_getmethods__ = {}
    for _s in [CKT_BASE]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, CMD, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def value_name(self):
        return _c_comand.CMD_value_name(self)

    def do_it(self, arg2, arg3):
        return _c_comand.CMD_do_it(self, arg2, arg3)
    __swig_destroy__ = _c_comand.delete_CMD
    __del__ = lambda self: None
    if _newclass:
        cmdproc = staticmethod(_c_comand.CMD_cmdproc)
    else:
        cmdproc = _c_comand.CMD_cmdproc
    if _newclass:
        command = staticmethod(_c_comand.CMD_command)
    else:
        command = _c_comand.CMD_command
CMD_swigregister = _c_comand.CMD_swigregister
CMD_swigregister(CMD)

def CMD_cmdproc(arg2, arg3):
    return _c_comand.CMD_cmdproc(arg2, arg3)
CMD_cmdproc = _c_comand.CMD_cmdproc

def CMD_command(arg2, arg3):
    return _c_comand.CMD_command(arg2, arg3)
CMD_command = _c_comand.CMD_command

# This file is compatible with both classic and new-style classes.


