# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_e_node')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_e_node')
    _e_node = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_e_node', [dirname(__file__)])
        except ImportError:
            import _e_node
            return _e_node
        try:
            _mod = imp.load_module('_e_node', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _e_node = swig_import_helper()
    del swig_import_helper
else:
    import _e_node
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

try:
    import weakref
    weakref_proxy = weakref.proxy
except __builtin__.Exception:
    weakref_proxy = lambda x: x


class node_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, node_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, node_t, name)
    __repr__ = _swig_repr

    def m_(self):
        return _e_node.node_t_m_(self)

    def t_(self):
        return _e_node.node_t_t_(self)

    def e_(self):
        return _e_node.node_t_e_(self)

    def short_label(self):
        return _e_node.node_t_short_label(self)

    def set_to_ground(self, arg2):
        return _e_node.node_t_set_to_ground(self, arg2)

    def new_node(self, arg2, arg3):
        return _e_node.node_t_new_node(self, arg2, arg3)

    def new_model_node(self, n, d):
        return _e_node.node_t_new_model_node(self, n, d)

    def map_subckt_node(self, map_array, d):
        return _e_node.node_t_map_subckt_node(self, map_array, d)

    def is_grounded(self):
        return _e_node.node_t_is_grounded(self)

    def is_connected(self):
        return _e_node.node_t_is_connected(self)

    def __init__(self, *args):
        this = _e_node.new_node_t(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _e_node.delete_node_t
    __del__ = lambda self: None

    def __deref__(self):
        return _e_node.node_t___deref__(self)

    def __eq__(self, p):
        return _e_node.node_t___eq__(self, p)

    def v0(self):
        return _e_node.node_t_v0(self)

    def vac(self):
        return _e_node.node_t_vac(self)

    def i(self):
        return _e_node.node_t_i(self)
node_t_swigregister = _e_node.node_t_swigregister
node_t_swigregister(node_t)

class nodearray_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, nodearray_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, nodearray_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["_t"] = _e_node.nodearray_t__t_set
    __swig_getmethods__["_t"] = _e_node.nodearray_t__t_get
    if _newclass:
        _t = _swig_property(_e_node.nodearray_t__t_get, _e_node.nodearray_t__t_set)

    def __getitem__(self, i):
        return _e_node.nodearray_t___getitem__(self, i)

    def __init__(self):
        this = _e_node.new_nodearray_t()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _e_node.delete_nodearray_t
    __del__ = lambda self: None
nodearray_t_swigregister = _e_node.nodearray_t_swigregister
nodearray_t_swigregister(nodearray_t)


def get_node(n, x):
    return _e_node.get_node(n, x)
get_node = _e_node.get_node
# This file is compatible with both classic and new-style classes.


