# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_gnucap_swig')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_gnucap_swig')
    _gnucap_swig = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_gnucap_swig', [dirname(__file__)])
        except ImportError:
            import _gnucap_swig
            return _gnucap_swig
        try:
            _mod = imp.load_module('_gnucap_swig', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _gnucap_swig = swig_import_helper()
    del swig_import_helper
else:
    import _gnucap_swig
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

try:
    import weakref
    weakref_proxy = weakref.proxy
except __builtin__.Exception:
    weakref_proxy = lambda x: x


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _gnucap_swig.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _gnucap_swig.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _gnucap_swig.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _gnucap_swig.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _gnucap_swig.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _gnucap_swig.SwigPyIterator_equal(self, x)

    def copy(self):
        return _gnucap_swig.SwigPyIterator_copy(self)

    def next(self):
        return _gnucap_swig.SwigPyIterator_next(self)

    def __next__(self):
        return _gnucap_swig.SwigPyIterator___next__(self)

    def previous(self):
        return _gnucap_swig.SwigPyIterator_previous(self)

    def advance(self, n):
        return _gnucap_swig.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _gnucap_swig.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _gnucap_swig.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _gnucap_swig.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _gnucap_swig.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _gnucap_swig.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _gnucap_swig.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _gnucap_swig.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

SHARED_PTR_DISOWN = _gnucap_swig.SHARED_PTR_DISOWN
BUFLEN = _gnucap_swig.BUFLEN
BIGBUFLEN = _gnucap_swig.BIGBUFLEN
I_PROMPT = _gnucap_swig.I_PROMPT
CKT_PROMPT = _gnucap_swig.CKT_PROMPT
ANTI_COMMENT = _gnucap_swig.ANTI_COMMENT
ENDDIR = _gnucap_swig.ENDDIR
PATHSEP = _gnucap_swig.PATHSEP
STEPFILE = _gnucap_swig.STEPFILE
rPRE_MAIN = _gnucap_swig.rPRE_MAIN
rPRESET = _gnucap_swig.rPRESET
rINTERACTIVE = _gnucap_swig.rINTERACTIVE
rSCRIPT = _gnucap_swig.rSCRIPT
rBATCH = _gnucap_swig.rBATCH
class ENV(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ENV, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ENV, name)
    __repr__ = _swig_repr
    __swig_setmethods__["run_mode"] = _gnucap_swig.ENV_run_mode_set
    __swig_getmethods__["run_mode"] = _gnucap_swig.ENV_run_mode_get
    if _newclass:
        run_mode = _swig_property(_gnucap_swig.ENV_run_mode_get, _gnucap_swig.ENV_run_mode_set)

    def __init__(self):
        this = _gnucap_swig.new_ENV()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _gnucap_swig.delete_ENV
    __del__ = lambda self: None
ENV_swigregister = _gnucap_swig.ENV_swigregister
ENV_swigregister(ENV)
cvar = _gnucap_swig.cvar

class COMPLEX_array_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, COMPLEX_array_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, COMPLEX_array_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["_t"] = _gnucap_swig.COMPLEX_array_t__t_set
    __swig_getmethods__["_t"] = _gnucap_swig.COMPLEX_array_t__t_get
    if _newclass:
        _t = _swig_property(_gnucap_swig.COMPLEX_array_t__t_get, _gnucap_swig.COMPLEX_array_t__t_set)

    def __getitem__(self, i):
        return _gnucap_swig.COMPLEX_array_t___getitem__(self, i)

    def __init__(self):
        this = _gnucap_swig.new_COMPLEX_array_t()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _gnucap_swig.delete_COMPLEX_array_t
    __del__ = lambda self: None
COMPLEX_array_t_swigregister = _gnucap_swig.COMPLEX_array_t_swigregister
COMPLEX_array_t_swigregister(COMPLEX_array_t)

class BSMATRIXd(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BSMATRIXd, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BSMATRIXd, name)
    __repr__ = _swig_repr

    def __init__(self, ss=0):
        this = _gnucap_swig.new_BSMATRIXd(ss)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def iwant(self, arg2, arg3):
        return _gnucap_swig.BSMATRIXd_iwant(self, arg2, arg3)

    def unallocate(self):
        return _gnucap_swig.BSMATRIXd_unallocate(self)

    def allocate(self):
        return _gnucap_swig.BSMATRIXd_allocate(self)

    def reallocate(self):
        return _gnucap_swig.BSMATRIXd_reallocate(self)

    def size(self):
        return _gnucap_swig.BSMATRIXd_size(self)

    def density(self):
        return _gnucap_swig.BSMATRIXd_density(self)

    def zero(self):
        return _gnucap_swig.BSMATRIXd_zero(self)

    def dezero(self, o):
        return _gnucap_swig.BSMATRIXd_dezero(self, o)

    def load_diagonal_point(self, i, value):
        return _gnucap_swig.BSMATRIXd_load_diagonal_point(self, i, value)

    def load_point(self, i, j, value):
        return _gnucap_swig.BSMATRIXd_load_point(self, i, j, value)

    def load_couple(self, i, j, value):
        return _gnucap_swig.BSMATRIXd_load_couple(self, i, j, value)

    def load_symmetric(self, i, j, value):
        return _gnucap_swig.BSMATRIXd_load_symmetric(self, i, j, value)

    def load_asymmetric(self, r1, r2, c1, c2, value):
        return _gnucap_swig.BSMATRIXd_load_asymmetric(self, r1, r2, c1, c2, value)

    def lu_decomp(self, *args):
        return _gnucap_swig.BSMATRIXd_lu_decomp(self, *args)

    def fbsub(self, x, b, c=None):
        return _gnucap_swig.BSMATRIXd_fbsub(self, x, b, c)

    def d(self, r, arg3):
        return _gnucap_swig.BSMATRIXd_d(self, r, arg3)
    __swig_destroy__ = _gnucap_swig.delete_BSMATRIXd
    __del__ = lambda self: None
BSMATRIXd_swigregister = _gnucap_swig.BSMATRIXd_swigregister
BSMATRIXd_swigregister(BSMATRIXd)

class BSMATRIXc(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BSMATRIXc, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BSMATRIXc, name)

    def __init__(self, ss=0):
        this = _gnucap_swig.new_BSMATRIXc(ss)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def iwant(self, arg2, arg3):
        return _gnucap_swig.BSMATRIXc_iwant(self, arg2, arg3)

    def unallocate(self):
        return _gnucap_swig.BSMATRIXc_unallocate(self)

    def allocate(self):
        return _gnucap_swig.BSMATRIXc_allocate(self)

    def reallocate(self):
        return _gnucap_swig.BSMATRIXc_reallocate(self)

    def size(self):
        return _gnucap_swig.BSMATRIXc_size(self)

    def density(self):
        return _gnucap_swig.BSMATRIXc_density(self)

    def zero(self):
        return _gnucap_swig.BSMATRIXc_zero(self)

    def dezero(self, o):
        return _gnucap_swig.BSMATRIXc_dezero(self, o)

    def load_diagonal_point(self, i, value):
        return _gnucap_swig.BSMATRIXc_load_diagonal_point(self, i, value)

    def load_point(self, i, j, value):
        return _gnucap_swig.BSMATRIXc_load_point(self, i, j, value)

    def load_couple(self, i, j, value):
        return _gnucap_swig.BSMATRIXc_load_couple(self, i, j, value)

    def load_symmetric(self, i, j, value):
        return _gnucap_swig.BSMATRIXc_load_symmetric(self, i, j, value)

    def load_asymmetric(self, r1, r2, c1, c2, value):
        return _gnucap_swig.BSMATRIXc_load_asymmetric(self, r1, r2, c1, c2, value)

    def lu_decomp(self, *args):
        return _gnucap_swig.BSMATRIXc_lu_decomp(self, *args)

    def fbsub(self, x, b, c=None):
        return _gnucap_swig.BSMATRIXc_fbsub(self, x, b, c)

    def d(self, r, arg3):
        return _gnucap_swig.BSMATRIXc_d(self, r, arg3)

    def fbsub_(self, x):
        return _gnucap_swig.BSMATRIXc_fbsub_(self, x)

    def __repr__(self):
        return _gnucap_swig.BSMATRIXc___repr__(self)

    def __getitem__(self, p):
        return _gnucap_swig.BSMATRIXc___getitem__(self, p)
    __swig_destroy__ = _gnucap_swig.delete_BSMATRIXc
    __del__ = lambda self: None
BSMATRIXc_swigregister = _gnucap_swig.BSMATRIXc_swigregister
BSMATRIXc_swigregister(BSMATRIXc)

class BSCR(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BSCR, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BSCR, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")

    def __repr__(self):
        return _gnucap_swig.BSCR___repr__(self)

    def __getitem__(self, *args):
        return _gnucap_swig.BSCR___getitem__(self, *args)
    __swig_destroy__ = _gnucap_swig.delete_BSCR
    __del__ = lambda self: None
BSCR_swigregister = _gnucap_swig.BSCR_swigregister
BSCR_swigregister(BSCR)

class SIM_DATA(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SIM_DATA, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SIM_DATA, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_setmethods__["_user_nodes"] = _gnucap_swig.SIM_DATA__user_nodes_set
    __swig_getmethods__["_user_nodes"] = _gnucap_swig.SIM_DATA__user_nodes_get
    if _newclass:
        _user_nodes = _swig_property(_gnucap_swig.SIM_DATA__user_nodes_get, _gnucap_swig.SIM_DATA__user_nodes_set)
    __swig_setmethods__["_subckt_nodes"] = _gnucap_swig.SIM_DATA__subckt_nodes_set
    __swig_getmethods__["_subckt_nodes"] = _gnucap_swig.SIM_DATA__subckt_nodes_get
    if _newclass:
        _subckt_nodes = _swig_property(_gnucap_swig.SIM_DATA__subckt_nodes_get, _gnucap_swig.SIM_DATA__subckt_nodes_set)
    __swig_setmethods__["_model_nodes"] = _gnucap_swig.SIM_DATA__model_nodes_set
    __swig_getmethods__["_model_nodes"] = _gnucap_swig.SIM_DATA__model_nodes_get
    if _newclass:
        _model_nodes = _swig_property(_gnucap_swig.SIM_DATA__model_nodes_get, _gnucap_swig.SIM_DATA__model_nodes_set)
    __swig_setmethods__["_total_nodes"] = _gnucap_swig.SIM_DATA__total_nodes_set
    __swig_getmethods__["_total_nodes"] = _gnucap_swig.SIM_DATA__total_nodes_get
    if _newclass:
        _total_nodes = _swig_property(_gnucap_swig.SIM_DATA__total_nodes_get, _gnucap_swig.SIM_DATA__total_nodes_set)
    __swig_setmethods__["_iter"] = _gnucap_swig.SIM_DATA__iter_set
    __swig_getmethods__["_iter"] = _gnucap_swig.SIM_DATA__iter_get
    if _newclass:
        _iter = _swig_property(_gnucap_swig.SIM_DATA__iter_get, _gnucap_swig.SIM_DATA__iter_set)
    __swig_setmethods__["_jomega"] = _gnucap_swig.SIM_DATA__jomega_set
    __swig_getmethods__["_jomega"] = _gnucap_swig.SIM_DATA__jomega_get
    if _newclass:
        _jomega = _swig_property(_gnucap_swig.SIM_DATA__jomega_get, _gnucap_swig.SIM_DATA__jomega_set)
    __swig_setmethods__["_limiting"] = _gnucap_swig.SIM_DATA__limiting_set
    __swig_getmethods__["_limiting"] = _gnucap_swig.SIM_DATA__limiting_get
    if _newclass:
        _limiting = _swig_property(_gnucap_swig.SIM_DATA__limiting_get, _gnucap_swig.SIM_DATA__limiting_set)
    __swig_setmethods__["_vmax"] = _gnucap_swig.SIM_DATA__vmax_set
    __swig_getmethods__["_vmax"] = _gnucap_swig.SIM_DATA__vmax_get
    if _newclass:
        _vmax = _swig_property(_gnucap_swig.SIM_DATA__vmax_get, _gnucap_swig.SIM_DATA__vmax_set)
    __swig_setmethods__["_vmin"] = _gnucap_swig.SIM_DATA__vmin_set
    __swig_getmethods__["_vmin"] = _gnucap_swig.SIM_DATA__vmin_get
    if _newclass:
        _vmin = _swig_property(_gnucap_swig.SIM_DATA__vmin_get, _gnucap_swig.SIM_DATA__vmin_set)
    __swig_setmethods__["_uic"] = _gnucap_swig.SIM_DATA__uic_set
    __swig_getmethods__["_uic"] = _gnucap_swig.SIM_DATA__uic_get
    if _newclass:
        _uic = _swig_property(_gnucap_swig.SIM_DATA__uic_get, _gnucap_swig.SIM_DATA__uic_set)
    __swig_setmethods__["_inc_mode"] = _gnucap_swig.SIM_DATA__inc_mode_set
    __swig_getmethods__["_inc_mode"] = _gnucap_swig.SIM_DATA__inc_mode_get
    if _newclass:
        _inc_mode = _swig_property(_gnucap_swig.SIM_DATA__inc_mode_get, _gnucap_swig.SIM_DATA__inc_mode_set)
    __swig_setmethods__["_mode"] = _gnucap_swig.SIM_DATA__mode_set
    __swig_getmethods__["_mode"] = _gnucap_swig.SIM_DATA__mode_get
    if _newclass:
        _mode = _swig_property(_gnucap_swig.SIM_DATA__mode_get, _gnucap_swig.SIM_DATA__mode_set)
    __swig_setmethods__["_phase"] = _gnucap_swig.SIM_DATA__phase_set
    __swig_getmethods__["_phase"] = _gnucap_swig.SIM_DATA__phase_get
    if _newclass:
        _phase = _swig_property(_gnucap_swig.SIM_DATA__phase_get, _gnucap_swig.SIM_DATA__phase_set)
    __swig_setmethods__["_nm"] = _gnucap_swig.SIM_DATA__nm_set
    __swig_getmethods__["_nm"] = _gnucap_swig.SIM_DATA__nm_get
    if _newclass:
        _nm = _swig_property(_gnucap_swig.SIM_DATA__nm_get, _gnucap_swig.SIM_DATA__nm_set)
    __swig_setmethods__["_i"] = _gnucap_swig.SIM_DATA__i_set
    __swig_getmethods__["_i"] = _gnucap_swig.SIM_DATA__i_get
    if _newclass:
        _i = _swig_property(_gnucap_swig.SIM_DATA__i_get, _gnucap_swig.SIM_DATA__i_set)
    __swig_setmethods__["_v0"] = _gnucap_swig.SIM_DATA__v0_set
    __swig_getmethods__["_v0"] = _gnucap_swig.SIM_DATA__v0_get
    if _newclass:
        _v0 = _swig_property(_gnucap_swig.SIM_DATA__v0_get, _gnucap_swig.SIM_DATA__v0_set)
    __swig_setmethods__["_vt1"] = _gnucap_swig.SIM_DATA__vt1_set
    __swig_getmethods__["_vt1"] = _gnucap_swig.SIM_DATA__vt1_get
    if _newclass:
        _vt1 = _swig_property(_gnucap_swig.SIM_DATA__vt1_get, _gnucap_swig.SIM_DATA__vt1_set)
    __swig_setmethods__["_ac"] = _gnucap_swig.SIM_DATA__ac_set
    __swig_getmethods__["_ac"] = _gnucap_swig.SIM_DATA__ac_get
    if _newclass:
        _ac = _swig_property(_gnucap_swig.SIM_DATA__ac_get, _gnucap_swig.SIM_DATA__ac_set)
    __swig_setmethods__["_nstat"] = _gnucap_swig.SIM_DATA__nstat_set
    __swig_getmethods__["_nstat"] = _gnucap_swig.SIM_DATA__nstat_get
    if _newclass:
        _nstat = _swig_property(_gnucap_swig.SIM_DATA__nstat_get, _gnucap_swig.SIM_DATA__nstat_set)
    __swig_setmethods__["_vdc"] = _gnucap_swig.SIM_DATA__vdc_set
    __swig_getmethods__["_vdc"] = _gnucap_swig.SIM_DATA__vdc_get
    if _newclass:
        _vdc = _swig_property(_gnucap_swig.SIM_DATA__vdc_get, _gnucap_swig.SIM_DATA__vdc_set)
    __swig_setmethods__["_aa"] = _gnucap_swig.SIM_DATA__aa_set
    __swig_getmethods__["_aa"] = _gnucap_swig.SIM_DATA__aa_get
    if _newclass:
        _aa = _swig_property(_gnucap_swig.SIM_DATA__aa_get, _gnucap_swig.SIM_DATA__aa_set)
    __swig_setmethods__["_lu"] = _gnucap_swig.SIM_DATA__lu_set
    __swig_getmethods__["_lu"] = _gnucap_swig.SIM_DATA__lu_get
    if _newclass:
        _lu = _swig_property(_gnucap_swig.SIM_DATA__lu_get, _gnucap_swig.SIM_DATA__lu_set)
    __swig_setmethods__["_acx"] = _gnucap_swig.SIM_DATA__acx_set
    __swig_getmethods__["_acx"] = _gnucap_swig.SIM_DATA__acx_get
    if _newclass:
        _acx = _swig_property(_gnucap_swig.SIM_DATA__acx_get, _gnucap_swig.SIM_DATA__acx_set)

    def is_first_expand(self):
        return _gnucap_swig.SIM_DATA_is_first_expand(self)

    def alloc_hold_vectors(self):
        return _gnucap_swig.SIM_DATA_alloc_hold_vectors(self)

    def alloc_vectors(self):
        return _gnucap_swig.SIM_DATA_alloc_vectors(self)

    def unalloc_vectors(self):
        return _gnucap_swig.SIM_DATA_unalloc_vectors(self)

    def uninit(self):
        return _gnucap_swig.SIM_DATA_uninit(self)

    def init(self):
        return _gnucap_swig.SIM_DATA_init(self)

    def set_command_none(self):
        return _gnucap_swig.SIM_DATA_set_command_none(self)

    def set_command_ac(self):
        return _gnucap_swig.SIM_DATA_set_command_ac(self)

    def set_command_dc(self):
        return _gnucap_swig.SIM_DATA_set_command_dc(self)

    def set_command_op(self):
        return _gnucap_swig.SIM_DATA_set_command_op(self)

    def set_command_tran(self):
        return _gnucap_swig.SIM_DATA_set_command_tran(self)

    def set_command_fourier(self):
        return _gnucap_swig.SIM_DATA_set_command_fourier(self)

    def sim_mode(self):
        return _gnucap_swig.SIM_DATA_sim_mode(self)

    def command_is_ac(self):
        return _gnucap_swig.SIM_DATA_command_is_ac(self)

    def command_is_dc(self):
        return _gnucap_swig.SIM_DATA_command_is_dc(self)

    def command_is_op(self):
        return _gnucap_swig.SIM_DATA_command_is_op(self)

    def analysis_is_ac(self):
        return _gnucap_swig.SIM_DATA_analysis_is_ac(self)

    def analysis_is_dcop(self):
        return _gnucap_swig.SIM_DATA_analysis_is_dcop(self)

    def analysis_is_static(self):
        return _gnucap_swig.SIM_DATA_analysis_is_static(self)

    def analysis_is_restore(self):
        return _gnucap_swig.SIM_DATA_analysis_is_restore(self)

    def analysis_is_tran(self):
        return _gnucap_swig.SIM_DATA_analysis_is_tran(self)

    def analysis_is_tran_static(self):
        return _gnucap_swig.SIM_DATA_analysis_is_tran_static(self)

    def analysis_is_tran_restore(self):
        return _gnucap_swig.SIM_DATA_analysis_is_tran_restore(self)

    def analysis_is_tran_dynamic(self):
        return _gnucap_swig.SIM_DATA_analysis_is_tran_dynamic(self)
    __swig_destroy__ = _gnucap_swig.delete_SIM_DATA
    __del__ = lambda self: None
SIM_DATA_swigregister = _gnucap_swig.SIM_DATA_swigregister
SIM_DATA_swigregister(SIM_DATA)

class PairDeque(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PairDeque, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PairDeque, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _gnucap_swig.PairDeque_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _gnucap_swig.PairDeque___nonzero__(self)

    def __bool__(self):
        return _gnucap_swig.PairDeque___bool__(self)

    def __len__(self):
        return _gnucap_swig.PairDeque___len__(self)

    def __getslice__(self, i, j):
        return _gnucap_swig.PairDeque___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _gnucap_swig.PairDeque___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _gnucap_swig.PairDeque___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _gnucap_swig.PairDeque___delitem__(self, *args)

    def __getitem__(self, *args):
        return _gnucap_swig.PairDeque___getitem__(self, *args)

    def __setitem__(self, *args):
        return _gnucap_swig.PairDeque___setitem__(self, *args)

    def pop(self):
        return _gnucap_swig.PairDeque_pop(self)

    def append(self, x):
        return _gnucap_swig.PairDeque_append(self, x)

    def empty(self):
        return _gnucap_swig.PairDeque_empty(self)

    def size(self):
        return _gnucap_swig.PairDeque_size(self)

    def swap(self, v):
        return _gnucap_swig.PairDeque_swap(self, v)

    def begin(self):
        return _gnucap_swig.PairDeque_begin(self)

    def end(self):
        return _gnucap_swig.PairDeque_end(self)

    def rbegin(self):
        return _gnucap_swig.PairDeque_rbegin(self)

    def rend(self):
        return _gnucap_swig.PairDeque_rend(self)

    def clear(self):
        return _gnucap_swig.PairDeque_clear(self)

    def get_allocator(self):
        return _gnucap_swig.PairDeque_get_allocator(self)

    def pop_back(self):
        return _gnucap_swig.PairDeque_pop_back(self)

    def erase(self, *args):
        return _gnucap_swig.PairDeque_erase(self, *args)

    def __init__(self, *args):
        this = _gnucap_swig.new_PairDeque(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _gnucap_swig.PairDeque_push_back(self, x)

    def front(self):
        return _gnucap_swig.PairDeque_front(self)

    def back(self):
        return _gnucap_swig.PairDeque_back(self)

    def assign(self, n, x):
        return _gnucap_swig.PairDeque_assign(self, n, x)

    def resize(self, *args):
        return _gnucap_swig.PairDeque_resize(self, *args)

    def insert(self, *args):
        return _gnucap_swig.PairDeque_insert(self, *args)

    def pop_front(self):
        return _gnucap_swig.PairDeque_pop_front(self)

    def push_front(self, x):
        return _gnucap_swig.PairDeque_push_front(self, x)
    __swig_destroy__ = _gnucap_swig.delete_PairDeque
    __del__ = lambda self: None
PairDeque_swigregister = _gnucap_swig.PairDeque_swigregister
PairDeque_swigregister(PairDeque)

class StopIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StopIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StopIterator, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _gnucap_swig.new_StopIterator()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _gnucap_swig.delete_StopIterator
    __del__ = lambda self: None
StopIterator_swigregister = _gnucap_swig.StopIterator_swigregister
StopIterator_swigregister(StopIterator)

class WaveIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, WaveIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, WaveIterator, name)
    __repr__ = _swig_repr

    def __init__(self, _cur, _end):
        this = _gnucap_swig.new_WaveIterator(_cur, _end)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def __iter__(self):
        return _gnucap_swig.WaveIterator___iter__(self)
    __swig_setmethods__["cur"] = _gnucap_swig.WaveIterator_cur_set
    __swig_getmethods__["cur"] = _gnucap_swig.WaveIterator_cur_get
    if _newclass:
        cur = _swig_property(_gnucap_swig.WaveIterator_cur_get, _gnucap_swig.WaveIterator_cur_set)
    __swig_setmethods__["end"] = _gnucap_swig.WaveIterator_end_set
    __swig_getmethods__["end"] = _gnucap_swig.WaveIterator_end_get
    if _newclass:
        end = _swig_property(_gnucap_swig.WaveIterator_end_get, _gnucap_swig.WaveIterator_end_set)

    def __next__(self):
        return _gnucap_swig.WaveIterator___next__(self)

    def next(self):
        return _gnucap_swig.WaveIterator_next(self)
    __swig_destroy__ = _gnucap_swig.delete_WaveIterator
    __del__ = lambda self: None
WaveIterator_swigregister = _gnucap_swig.WaveIterator_swigregister
WaveIterator_swigregister(WaveIterator)

class WAVE(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, WAVE, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, WAVE, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _gnucap_swig.new_WAVE(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _gnucap_swig.delete_WAVE
    __del__ = lambda self: None

    def set_delay(self, d):
        return _gnucap_swig.WAVE_set_delay(self, d)

    def initialize(self):
        return _gnucap_swig.WAVE_initialize(self)

    def push(self, t, v):
        return _gnucap_swig.WAVE_push(self, t, v)

    def v_out(self, t):
        return _gnucap_swig.WAVE_v_out(self, t)

    def v_reflect(self, t, v_total):
        return _gnucap_swig.WAVE_v_reflect(self, t, v_total)

    def __iadd__(self, *args):
        return _gnucap_swig.WAVE___iadd__(self, *args)

    def __imul__(self, *args):
        return _gnucap_swig.WAVE___imul__(self, *args)

    def begin(self):
        return _gnucap_swig.WAVE_begin(self)

    def end(self):
        return _gnucap_swig.WAVE_end(self)

    def __iter__(self):
        return _gnucap_swig.WAVE___iter__(self)
WAVE_swigregister = _gnucap_swig.WAVE_swigregister
WAVE_swigregister(WAVE)

class CKT_BASE(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CKT_BASE, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CKT_BASE, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    if _newclass:
        find_wave = staticmethod(_gnucap_swig.CKT_BASE_find_wave)
    else:
        find_wave = _gnucap_swig.CKT_BASE_find_wave
CKT_BASE_swigregister = _gnucap_swig.CKT_BASE_swigregister
CKT_BASE_swigregister(CKT_BASE)

def CKT_BASE_find_wave(arg2):
    return _gnucap_swig.CKT_BASE_find_wave(arg2)
CKT_BASE_find_wave = _gnucap_swig.CKT_BASE_find_wave

class CMD(CKT_BASE):
    __swig_setmethods__ = {}
    for _s in [CKT_BASE]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, CMD, name, value)
    __swig_getmethods__ = {}
    for _s in [CKT_BASE]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, CMD, name)
    __repr__ = _swig_repr

    def value_name(self):
        return _gnucap_swig.CMD_value_name(self)

    def do_it(self, arg0, arg1):
        return _gnucap_swig.CMD_do_it(self, arg0, arg1)
    __swig_destroy__ = _gnucap_swig.delete_CMD
    __del__ = lambda self: None
    if _newclass:
        cmdproc = staticmethod(_gnucap_swig.CMD_cmdproc)
    else:
        cmdproc = _gnucap_swig.CMD_cmdproc
    if _newclass:
        command = staticmethod(_gnucap_swig.CMD_command)
    else:
        command = _gnucap_swig.CMD_command

    def __init__(self):
        if self.__class__ == CMD:
            _self = None
        else:
            _self = self
        this = _gnucap_swig.new_CMD(_self, )
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    def __disown__(self):
        self.this.disown()
        _gnucap_swig.disown_CMD(self)
        return weakref_proxy(self)
CMD_swigregister = _gnucap_swig.CMD_swigregister
CMD_swigregister(CMD)

def CMD_cmdproc(arg2, arg3):
    return _gnucap_swig.CMD_cmdproc(arg2, arg3)
CMD_cmdproc = _gnucap_swig.CMD_cmdproc

def CMD_command(arg2, arg3):
    return _gnucap_swig.CMD_command(arg2, arg3)
CMD_command = _gnucap_swig.CMD_command

class SIM(CMD):
    __swig_setmethods__ = {}
    for _s in [CMD]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SIM, name, value)
    __swig_getmethods__ = {}
    for _s in [CMD]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, SIM, name)
    __repr__ = _swig_repr

    def __init__(self):
        if self.__class__ == SIM:
            _self = None
        else:
            _self = self
        this = _gnucap_swig.new_SIM(_self, )
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _gnucap_swig.delete_SIM
    __del__ = lambda self: None

    def setup(self, arg0):
        return _gnucap_swig.SIM_setup(self, arg0)

    def sweep(self):
        return _gnucap_swig.SIM_sweep(self)

    def outdata(self, arg0, arg1):
        return _gnucap_swig.SIM_outdata(self, arg0, arg1)

    def head(self, arg0, arg1, arg2):
        return _gnucap_swig.SIM_head(self, arg0, arg1, arg2)

    def print_results(self, arg0):
        return _gnucap_swig.SIM_print_results(self, arg0)

    def alarm(self):
        return _gnucap_swig.SIM_alarm(self)

    def store_results(self, arg0):
        return _gnucap_swig.SIM_store_results(self, arg0)

    def advance_time(self):
        return _gnucap_swig.SIM_advance_time(self)

    def sim_(self):
        return _gnucap_swig.SIM_sim_(self)
    def __disown__(self):
        self.this.disown()
        _gnucap_swig.disown_SIM(self)
        return weakref_proxy(self)
SIM_swigregister = _gnucap_swig.SIM_swigregister
SIM_swigregister(SIM)

class SIM_(SIM):
    __swig_setmethods__ = {}
    for _s in [SIM]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SIM_, name, value)
    __swig_getmethods__ = {}
    for _s in [SIM]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, SIM_, name)
    __repr__ = _swig_repr

    def __init__(self):
        if self.__class__ == SIM_:
            _self = None
        else:
            _self = self
        this = _gnucap_swig.new_SIM_(_self, )
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def setup(self, arg0):
        return _gnucap_swig.SIM__setup(self, arg0)

    def sweep(self):
        return _gnucap_swig.SIM__sweep(self)

    def do_it(self, arg0, arg1):
        return _gnucap_swig.SIM__do_it(self, arg0, arg1)

    def outdata(self, d, i):
        return _gnucap_swig.SIM__outdata(self, d, i)

    def head(self, a, b, s):
        return _gnucap_swig.SIM__head(self, a, b, s)

    def solve(self, a, b):
        return _gnucap_swig.SIM__solve(self, a, b)

    def solve_with_homotopy(self, a, b):
        return _gnucap_swig.SIM__solve_with_homotopy(self, a, b)
    def __disown__(self):
        self.this.disown()
        _gnucap_swig.disown_SIM_(self)
        return weakref_proxy(self)

    def print_results(self, arg0):
        return _gnucap_swig.SIM__print_results(self, arg0)

    def alarm(self):
        return _gnucap_swig.SIM__alarm(self)

    def store_results(self, arg0):
        return _gnucap_swig.SIM__store_results(self, arg0)
SIM__swigregister = _gnucap_swig.SIM__swigregister
SIM__swigregister(SIM_)

class TRANSIENT(SIM):
    __swig_setmethods__ = {}
    for _s in [SIM]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TRANSIENT, name, value)
    __swig_getmethods__ = {}
    for _s in [SIM]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, TRANSIENT, name)
    __repr__ = _swig_repr

    def do_it(self, arg0, scope):
        return _gnucap_swig.TRANSIENT_do_it(self, arg0, scope)

    def __init__(self):
        if self.__class__ == TRANSIENT:
            _self = None
        else:
            _self = self
        this = _gnucap_swig.new_TRANSIENT(_self, )
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _gnucap_swig.delete_TRANSIENT
    __del__ = lambda self: None

    def accept(self):
        return _gnucap_swig.TRANSIENT_accept(self)
    __swig_setmethods__["_cont"] = _gnucap_swig.TRANSIENT__cont_set
    __swig_getmethods__["_cont"] = _gnucap_swig.TRANSIENT__cont_get
    if _newclass:
        _cont = _swig_property(_gnucap_swig.TRANSIENT__cont_get, _gnucap_swig.TRANSIENT__cont_set)

    def sweep(self):
        return _gnucap_swig.TRANSIENT_sweep(self)

    def outdata(self, arg0, arg1):
        return _gnucap_swig.TRANSIENT_outdata(self, arg0, arg1)
    def __disown__(self):
        self.this.disown()
        _gnucap_swig.disown_TRANSIENT(self)
        return weakref_proxy(self)

    def setup(self, arg0):
        return _gnucap_swig.TRANSIENT_setup(self, arg0)

    def head(self, arg0, arg1, arg2):
        return _gnucap_swig.TRANSIENT_head(self, arg0, arg1, arg2)

    def print_results(self, arg0):
        return _gnucap_swig.TRANSIENT_print_results(self, arg0)

    def alarm(self):
        return _gnucap_swig.TRANSIENT_alarm(self)

    def store_results(self, arg0):
        return _gnucap_swig.TRANSIENT_store_results(self, arg0)
TRANSIENT_swigregister = _gnucap_swig.TRANSIENT_swigregister
TRANSIENT_swigregister(TRANSIENT)


def command(command):
    return _gnucap_swig.command(command)
command = _gnucap_swig.command

def parse(command):
    return _gnucap_swig.parse(command)
parse = _gnucap_swig.parse
# This file is compatible with both classic and new-style classes.


