# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_m_cpoly')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_m_cpoly')
    _m_cpoly = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_m_cpoly', [dirname(__file__)])
        except ImportError:
            import _m_cpoly
            return _m_cpoly
        try:
            _mod = imp.load_module('_m_cpoly', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _m_cpoly = swig_import_helper()
    del swig_import_helper
else:
    import _m_cpoly
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

try:
    import weakref
    weakref_proxy = weakref.proxy
except __builtin__.Exception:
    weakref_proxy = lambda x: x


class FPOLY1(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FPOLY1, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FPOLY1, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _m_cpoly.FPOLY1_x_set
    __swig_getmethods__["x"] = _m_cpoly.FPOLY1_x_get
    if _newclass:
        x = _swig_property(_m_cpoly.FPOLY1_x_get, _m_cpoly.FPOLY1_x_set)
    __swig_setmethods__["f0"] = _m_cpoly.FPOLY1_f0_set
    __swig_getmethods__["f0"] = _m_cpoly.FPOLY1_f0_get
    if _newclass:
        f0 = _swig_property(_m_cpoly.FPOLY1_f0_get, _m_cpoly.FPOLY1_f0_set)
    __swig_setmethods__["f1"] = _m_cpoly.FPOLY1_f1_set
    __swig_getmethods__["f1"] = _m_cpoly.FPOLY1_f1_get
    if _newclass:
        f1 = _swig_property(_m_cpoly.FPOLY1_f1_get, _m_cpoly.FPOLY1_f1_set)

    def __init__(self, *args):
        this = _m_cpoly.new_FPOLY1(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _m_cpoly.delete_FPOLY1
    __del__ = lambda self: None

    def __eq__(self, p):
        return _m_cpoly.FPOLY1___eq__(self, p)

    def __imul__(self, *args):
        return _m_cpoly.FPOLY1___imul__(self, *args)

    def __iadd__(self, *args):
        return _m_cpoly.FPOLY1___iadd__(self, *args)

    def __neg__(self):
        return _m_cpoly.FPOLY1___neg__(self)

    def c1(self):
        return _m_cpoly.FPOLY1_c1(self)

    def c0(self):
        return _m_cpoly.FPOLY1_c0(self)
FPOLY1_swigregister = _m_cpoly.FPOLY1_swigregister
FPOLY1_swigregister(FPOLY1)

class CPOLY1(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CPOLY1, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CPOLY1, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _m_cpoly.CPOLY1_x_set
    __swig_getmethods__["x"] = _m_cpoly.CPOLY1_x_get
    if _newclass:
        x = _swig_property(_m_cpoly.CPOLY1_x_get, _m_cpoly.CPOLY1_x_set)
    __swig_setmethods__["c0"] = _m_cpoly.CPOLY1_c0_set
    __swig_getmethods__["c0"] = _m_cpoly.CPOLY1_c0_get
    if _newclass:
        c0 = _swig_property(_m_cpoly.CPOLY1_c0_get, _m_cpoly.CPOLY1_c0_set)
    __swig_setmethods__["c1"] = _m_cpoly.CPOLY1_c1_set
    __swig_getmethods__["c1"] = _m_cpoly.CPOLY1_c1_get
    if _newclass:
        c1 = _swig_property(_m_cpoly.CPOLY1_c1_get, _m_cpoly.CPOLY1_c1_set)

    def __init__(self, *args):
        this = _m_cpoly.new_CPOLY1(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _m_cpoly.delete_CPOLY1
    __del__ = lambda self: None

    def __eq__(self, p):
        return _m_cpoly.CPOLY1___eq__(self, p)

    def __imul__(self, s):
        return _m_cpoly.CPOLY1___imul__(self, s)

    def f1(self):
        return _m_cpoly.CPOLY1_f1(self)

    def f0(self):
        return _m_cpoly.CPOLY1_f0(self)
CPOLY1_swigregister = _m_cpoly.CPOLY1_swigregister
CPOLY1_swigregister(CPOLY1)

# This file is compatible with both classic and new-style classes.


