# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_u_opt')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_u_opt')
    _u_opt = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_u_opt', [dirname(__file__)])
        except ImportError:
            import _u_opt
            return _u_opt
        try:
            _mod = imp.load_module('_u_opt', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _u_opt = swig_import_helper()
    del swig_import_helper
else:
    import _u_opt
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

try:
    import weakref
    weakref_proxy = weakref.proxy
except __builtin__.Exception:
    weakref_proxy = lambda x: x


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _u_opt.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _u_opt.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _u_opt.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _u_opt.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _u_opt.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _u_opt.SwigPyIterator_equal(self, x)

    def copy(self):
        return _u_opt.SwigPyIterator_copy(self)

    def next(self):
        return _u_opt.SwigPyIterator_next(self)

    def __next__(self):
        return _u_opt.SwigPyIterator___next__(self)

    def previous(self):
        return _u_opt.SwigPyIterator_previous(self)

    def advance(self, n):
        return _u_opt.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _u_opt.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _u_opt.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _u_opt.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _u_opt.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _u_opt.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _u_opt.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _u_opt.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

BUFLEN = _u_opt.BUFLEN
BIGBUFLEN = _u_opt.BIGBUFLEN
I_PROMPT = _u_opt.I_PROMPT
CKT_PROMPT = _u_opt.CKT_PROMPT
ANTI_COMMENT = _u_opt.ANTI_COMMENT
ENDDIR = _u_opt.ENDDIR
PATHSEP = _u_opt.PATHSEP
STEPFILE = _u_opt.STEPFILE
rPRE_MAIN = _u_opt.rPRE_MAIN
rPRESET = _u_opt.rPRESET
rINTERACTIVE = _u_opt.rINTERACTIVE
rSCRIPT = _u_opt.rSCRIPT
rBATCH = _u_opt.rBATCH
class ENV(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ENV, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ENV, name)
    __repr__ = _swig_repr
    __swig_setmethods__["run_mode"] = _u_opt.ENV_run_mode_set
    __swig_getmethods__["run_mode"] = _u_opt.ENV_run_mode_get
    if _newclass:
        run_mode = _swig_property(_u_opt.ENV_run_mode_get, _u_opt.ENV_run_mode_set)

    def __init__(self):
        this = _u_opt.new_ENV()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _u_opt.delete_ENV
    __del__ = lambda self: None
ENV_swigregister = _u_opt.ENV_swigregister
ENV_swigregister(ENV)
cvar = _u_opt.cvar

class COMPLEX_array_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, COMPLEX_array_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, COMPLEX_array_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["_t"] = _u_opt.COMPLEX_array_t__t_set
    __swig_getmethods__["_t"] = _u_opt.COMPLEX_array_t__t_get
    if _newclass:
        _t = _swig_property(_u_opt.COMPLEX_array_t__t_get, _u_opt.COMPLEX_array_t__t_set)

    def __getitem__(self, i):
        return _u_opt.COMPLEX_array_t___getitem__(self, i)

    def __init__(self):
        this = _u_opt.new_COMPLEX_array_t()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _u_opt.delete_COMPLEX_array_t
    __del__ = lambda self: None
COMPLEX_array_t_swigregister = _u_opt.COMPLEX_array_t_swigregister
COMPLEX_array_t_swigregister(COMPLEX_array_t)

class SET_RUN_MODE(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SET_RUN_MODE, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SET_RUN_MODE, name)
    __repr__ = _swig_repr

    def __init__(self, rm):
        this = _u_opt.new_SET_RUN_MODE(rm)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _u_opt.delete_SET_RUN_MODE
    __del__ = lambda self: None
SET_RUN_MODE_swigregister = _u_opt.SET_RUN_MODE_swigregister
SET_RUN_MODE_swigregister(SET_RUN_MODE)

# This file is compatible with both classic and new-style classes.


